### ISSUE TITLE
[Discussion] Is a registry-service necessary?

### ISSUE THREAD

**Issue by Frozen-byte** [kreuzerk/svg-icon-library-starter#10]
Hey 🚀 
I have a quick question: Is there anything problematic not using the registry-service given by the example app?
I think it is inconvenient to Import the SVG-Object, then remember the name and use it in the Template.

Do you have any thoughts on the downsides of using the object directly?

I have written this SVGComponent in my library:
```ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  OnChanges,
  Renderer2,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MyIcon } from './my-icons';

@Component({
  selector: 'my-icon[icon]',
  templateUrl: './icon.component.html',
  styleUrls: ['./icon.component.scss'],
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconComponent implements OnChanges {
  @Input() public icon!: MyIcon;

  private svgIcon?: SVGElement;

  constructor(
    private element: ElementRef,
    private renderer: Renderer2,
  ) {}

  ngOnChanges(changes: NgChanges<IconComponent>) {
    const currentSvgData = changes.icon?.currentValue?.data;
    const previousSvgData = changes.icon?.previousValue?.data;

    if (currentSvgData !== previousSvgData) {
      if (this.element && this.svgIcon) {
        this.renderer.removeChild(this.element.nativeElement, this.svgIcon);
      }

      if (currentSvgData) {
        this.svgIcon = this.svgElementFromString(currentSvgData);
        this.renderer.appendChild(this.element.nativeElement, this.svgIcon);
      }
    }
  }

  private svgElementFromString(svgContent: string): SVGElement {
    const div = this.renderer.createElement('svg');
    div.innerHTML = svgContent;
    return (
      div.querySelector('svg') ||
      this.renderer.createElement('path', 'http://www.w3.org/2000/svg')
    );
  }
}
```

And my Consumer-Application does implement it as follows:
```ts
import { IconComponent, MyIconCheckMark1 } from "@my-lib/icons";

@Component({
  selector: "my-icon-consumer",
  standalone: true,
  imports: [IconComponent],
  template: '<my-icon [icon]="MyIconCheckMark1"></my-icon>',
  styleUrl: "icon-consumer.scss",
})
export class IconConsumerComponent {
  public MyIconCheckMark1 = MyIconCheckMark1;
}
```

**Comment by nivekcode** [comment]
Hey, @Frozen-byte the registry is usually needed for tree shaking and to optimize bundle size. But I guess your approach also works since you are importing the Icon and making it available as a public property on the component which should be analyzable by a bundler (to be 100% sure I would recommend you to double check this). I also expect the tree shaking and splitting to only work if the icons where generated with the files conversion of svg-to-ts. Object conversion probably only supports shaking but not splitting.

With your approach you do not need to register the icons in a registry, however you need to import and provide them for every component, which I guess nowadays that we have standalone this makes more sense from a conceptual point of view. With the help of a registry you could register Icons for a whole lazy loaded feature. In the end its also a bit of preference and personal taste I guess. 

```
public MyIconCheckMark1 = MyIconCheckMark1;
```
vs:

```typescript
inject(MyRegistry).registerIcons([MyIconCheckMark1]);
```

If the tree shaking and splitting works I don't see an issue with your approach.
